Repository 21jun/2048, pull requests merged in 2019-05, with the labels that each got.

#6 refactor : slideArray의 parameter 형식을 변경함
  2048.c
Labels: enhancement

#7 docs: main함수 주석 한글화함, todo리스트 작성함
  2048.c
  2048.dSYM/Contents/Info.plist
Labels: Docs, enhancement

#5 docs: 맡은 파트(move)의 head comment 를 추가함
  2048.c
Labels: Docs
